version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.3
    - 24.1.4
    - 24.1.5
    - 24.1.7
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.0
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.10.0
    - 4.15.2
    - 4.16.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 3.10.1
  - dependency-name: lodash
    versions:
    - 4.17.20
